CREATE DATABASE IF NOT EXISTS examenfinal12;
USE examenfinal12;
USE examenfinal12;

ALTER TABLE vehiculo12
MODIFY COLUMN PRECIO_12 DECIMAL(20,2) NOT NULL;

CREATE TABLE vehiculo12 (
  ID_VEHICULO_12 INT AUTO_INCREMENT PRIMARY KEY,
  MARCA_12      VARCHAR(100) NOT NULL,
  MODELO_12     VARCHAR(100) NOT NULL,
  PRECIO_12     DECIMAL(10,2) NOT NULL,
  CANTIDAD_12   INT NOT NULL
);
